name: HsRails
version: 1.0-SNAPSHOT
description: High speed minecart rails
api-version: 1.17
main: xyz.holocons.mc.hsrails.HsRails
commands:
  hsrails:
    description: Sets new minecart speed limit.
    usage: /hsrails <multiplier>
permissions:
  hsrails.cmd:
    description: Allows you to use speed cmd
    default: op
