name: HsRails
version: 2.0.1
description: High speed minecart rails
api-version: 1.16
main: st.netb.mc.hsrails.HsRails
commands:
  hsrails:
    description: Sets new minecart speed limit.
    usage: /hsrails <multiplier>
permissions:
  hsrails.cmd:
    description: Allows you to use speed cmd
    default: op
